### ISSUE TITLE
We need a find method in the Model class

### ISSUE THREAD

**Issue by wilsonge** [joomla-projects/entities#4]
To find a data item you need to call

```
$populatedModel = (new UserModel($this->db))->newQuery()->find($primaryKey);
```

which involves creating two model instances - which is kinda suboptimal :/

**Comment by isacandrei** [comment]
This is the way we currently do find:

```
$model = new User(self::$driver);
$user = $model->find(42);
```

I am not even sure how you managed to do it without passing the DatabaseDriver.

`find` is magically called on a new instance of a query:

```
return $this->newQuery()->$method(...$parameters);
```

**Comment by isacandrei** [comment]
Going back to the discussing of static methods, the only way I see (maybe easy way) finding a row is to have a static method which receives the DatabaseDriver as a parameter.

Alternatively, we can change the `find` method in the `Query` to alter and return the current instance of the Model. But, this means we would have different flows for when we return one instance(reuse the model attribute from the query) vs multiple instances (recreate them all as new instances - hydrate).

**Comment by isacandrei** [comment]
I'll make another issue for that to keep track of it.

**Comment by wilsonge** [comment]
Cool! Closing this then :)
