### ISSUE TITLE
setAttribute needs to check the key is known

### ISSUE THREAD

**Issue by wilsonge** [joomla-projects/entities#5]
After we apply the alias we need to check if the key is a valid attribute and throw an exception if it's not

Maybe introduce the property of virtual properties to deal with the fact that there maybe properties we split up (e.g. in the CMS com_content's articletext)

**Comment by isacandrei** [comment]
Different issues can occur by solving this issues.

For Relations that are eager loaded with constraints(e.g. selecting only e few columns) we cannot assume that if an attribute that the user want to set, is not among the $attributes, $columnAliases and $setMutators does not exist and throw an exception.

Also this may occur if we load a simple Model instance with just a few columns.

**Comment by isacandrei** [comment]
Added commit https://github.com/joomla-projects/entities/pull/9/commits/9145baeefbd4c3f46146c172e9be8509296d9dd5 in PR https://github.com/joomla-projects/entities/pull/9
